package define;

public enum GameError {
	OK(200, "OK") {
	},
	PARAM_ERROR(201, "PARAM FORMAT ERROR") {
	},
	INVALID_PARAM(202, "INVALID PARAM VALUE") {
	},
	MSG_LEN(203, "MSG LENTH ERROR") {
	},
	DDOS_ERROR(204, "SEND MSG TOO FAST") {
	},
	PROTOCAL_ERROR(205, "WRONG ENCODE") {
	},
	SERVER_EXCEPTION(206, "OCCUR EXCEPTION") {
	},
	CUR_VERSION(207, "CURRENT VERSION OLD") {// 版本有更新，请退出重进
	},
	SESSION_LOST(208, "SESSION LOST") {// SESSION失效，请重新登录
	},
	TOKEN_LOST(209, "TOKEN LOST") {// token丢失，请重新登录
	},
	NO_LORD(210, "NOT FOUND LORD") {
	},
	SENSITIVE_WORD(211, "CONTAIN SENSITIVE WORD") {
	},
	INVALID_CHAR(212, "INVALID CHAR") {
	},

	SAME_NICK(501, "SAME NICK NAME") {
	},
	ALREADY_CREATE(502, "ALREADY CREATE ROLE") {
	},
	NO_REPAIR(503, "NO NEED REPAIR") {
	},
	NO_CONFIG(504, "NO CONFIG") {
	},
	DATA_EXCEPTION(505, "PLAYER DATA EXCEPTION") {
	},
	STONE_NOT_ENOUGH(506, "STONE NOT ENOUGH") {
	},
	GOLD_NOT_ENOUGH(507, "GOLD NOT ENOUGH") {
	},
	LV_NOT_ENOUGH(508, "LORD LEVEL NOT ENOUGH") {
	},
	COMMAND_LV_NOT_ENOUGH(509, "COMMAND LEVEL NOT ENOUGH") {
	},
	RESOURCE_NOT_ENOUGH(510, "RESOURCE NOT ENOUGH") {
	},
	MAX_BUILD_QUE(511, "MAX BUILD QUE") {
	},
	ALREADY_BUILD(512, "ALREADY IN BUILD QUE") {
	},
	CANT_BUILD(513, "THIS CAN'T BE BUILD") {
	},
	BUILD_LEVEL(514, "BUILD LEVEL NOT ENOUGH") {
	},
	MAX_TANK_QUE(515, "MAX TANK QUE") {
	},
	NO_EXIST_QUE(516, "NOT FOUND THIS QUE") {
	},
	NO_PROP(517, "DON'T HAVA PROP") {
	},
	BOOK_NOT_ENOUGH(518, "SKILL BOOK NOT ENOUGH") {
	},
	MAX_PROP_QUE(519, "MAX PROP QUE") {
	},
	SPEED_WAIT_QUE(520, "CAN'T SPEED WAIT QUE") {
	},
	CANT_REFIT(521, "THIS CAN'T BE REFIT") {
	},
	DRAWING_NOT_ENOUGH(522, "DRWAING NOT ENOUGH") {
	},
	HERO_CHIP_NOT_ENOUGH(523, "HERO CHIP NOT ENOUGH") {
	},
	PROP_NOT_ENOUGH(524, "PROP NOT ENOUGH") {
	},
	MAX_REFIT_QUE(525, "MAX REFIT QUE") {
	},
	TANK_COUNT(526, "TANK COUNT NOT ENOUGHT") {
	},
	NO_EQUIP(527, "DON'T HAVA THIS EQUIP") {
	},
	MAX_EQUIP_LV(528, "MAX EQUIP LEVEL") {
	},
	ALRADY_EQUIP(529, "ALREADY EQUIP") {
	},
	MAX_EQUIP_STORE(530, "MAX EQUIP STORE") {
	},
	FULL_EQUIP_ON(531, "FULL EQUIP ON") {
	},
	EQUIP_STORE_LIMIT(532, "STORE LIMIT") {
	},
	CHIP_NOT_ENOUGH(533, "PART CHIP NOT ENOUGH") {
	},
	NO_PART(534, "DON'T HAVA THIS PART") {
	},
	MAX_PART_UP_LV(535, "MAX PART UP LV") {
	},
	METAL_NOT_ENOUGH(536, "METAL NOT ENOUGH") {
	},
	MAX_PART_REFIT_LV(537, "MAX PART REFIT LV") {
	},
	INGREDIENT_NOT_ENOUGH(538, "INGREDIENT NOT ENOUGH") {
	},
	DRAW_NOT_ENOUGH(539, "DRAW NOT ENOUGH") {
	},
	FULL_PART_ON(540, "FULL PART ON") {
	},
	MAX_PART_STORE(541, "MAX PART STORE") {
	},
	FAME_LEVEL_ERROR(542, "FAME LEVEL NOT ENOUGH") {
	},
	COMBAT_PASS_BEFORE(543, "DON'T PASS BEFORE") {
	},
	NO_POWER(544, "POWER NOT ENOUGH") {
	},
	NO_RANKS(545, "LORD RANKS NOT ENOUGH") {
	},
	HAD_PASS(546, "HAD PASS THIS EXTREME EXPLORE") {
	},
	NEED_3STAR(547, "NEED 3 STAR") {
	},
	VIP_NOT_ENOUGH(548, "VIP NOT ENOUGH") {
	},
	COMBAT_NOT_OPEN(549, "COMBAT NOT OPEN") {
	},
	MAX_BUY_COUNT(550, "MAX BUY COUNT") {
	},
	HERO_CANT_UP(551, "HERO CANT UP") {
	},
	NO_PASS(552, "WIPE UNPASS COMBAT") {
	},
	NO_STAR(553, "COMBAT STAR NOT ENOUGH") {
	},
	HUANGBAO_NOT_ENOUGH(554, "HUANGBAO NOT ENOUGH") {
	},
	MAX_RANKS(555, "MAX RANKS") {

	},
	MAX_COMMAND(556, "MAX COMMAND") {

	},
	FULL_PROSP(557, "FULL PROSP") {

	},
	ALREADY_FAME(558, "ALREADY FAME") {

	},
	ALREADY_GET_BOX(559, "ALREADY GET BOX") {

	},
	ALREADY_RANK_FAME(560, "ALREADY GET RANK FAME") {

	},
	FRIEND_HAD(561, "FRIEND HAD") {
	},
	FRIEND_NOT_EXIST(562, "FRIEND NOT EXIST") {
	},
	BLESS_HAD(563, "BLESS HAD") {
	},
	NO_BUILDING(564, "NO BUILDING") {
	},
	ALREADY_MILL(565, "ALREADY HAD MILL AT POS") {
	},
	MAX_MILL(566, "EXCESS MILL COUNT LIMIT") {
	},
	PLAYER_NOT_EXIST(567, "PLAYER NOT EXIST") {
	},
	NO_HERO(568, "NO HERO") {
	},
	ARENA_COUNT(569, "EXCESS ARENA COUNT") {
	},
	ARENA_FORM(570, "NO ARENA FORM") {
	},
	ARENA_CD(571, "ARENA CD") {
	},
	NOT_HERO(572, "IT'S NOT HERO") {
	},
	MAX_BUY_ARENA(573, "MAX BUY ARENA") {
	},
	ARENA_SCORE(574, "ARENA SCORE NOT ENOUGH") {
	},
	NO_EXPLORE_COUNT(578, "NO EXPLORE COUNT") {
	},
	RANK_NOT_ENOUGH(579, "RANK NOT ENOUGH") {
	},
	ALREADY_ARENA_AWARD(580, "ALREADY GET AWARD") {
	},
	NO_PARTY(581, "NO PARTY") {
	},
	PARTY_NOT_EXIST(582, "PARTY NOT EXIST") {
	},
	DONATE_COUNT(583, "DONATE COUNT") {
	},
	AUTHORITY_ERR(584, "AUTHORITY_ERR") {
	},
	DONATE_NOT_ENOUGH(585, "DONATE NOT ENOUGH") {
	},
	WEAL_NOT_EXIST(586, "WEAL NOT EXIST") {
	},
	WEAL_GOT(587, "WEAL GOT") {
	},
	PARTY_HAD(588, "PARTY HAD") {
	},
	SAME_PARTY_NAME(589, "SAME PARTY NAME") {
	},
	PARTY_APPLY_FULL(590, "PARTY APPLY FULL") {
	},
	FIGHT_NOT_ENOUGH(591, "FIGHT NOT ENOUGH") {
	},
	PARTY_MEMBER_FULL(592, "PARTY MEMBER FULL") {
	},
	EMPTY_POS(593, "EMPTY POS") {
	},
	MAX_ARMY_COUNT(594, "MAX ARMY COUNT") {
	},
	UP_JOB_FAIL(595, "UP JOB FAIL") {
	},
	PARTY_COMBAT_EXIST(596, "PARTY_COMBAT_EXIST") {
	},
	AWARD_HAD_GOT(597, "AWARD HAD GOT") {
	},
	COMBAT_PASS(598, "COMBAT PASS") {
	},
	POS_NOT_EMPTY(599, "POS NOT EMPTY") {
	},
	NO_ARMY(600, "NO ARMY") {
	},
	IN_MARCH(601, "IN MARCHING") {
	},
	MAIL_NOT_EXIST(602, "MAIL NOT EXIST") {
	},
	NOT_IN_MARCH(603, "NOT IN MARCHING") {
	},
	UN_LOGIN(604, "UN LOGIN") {
	},
	NO_TASK(605, "NO TASK") {
	},
	TASK_NO_FINISH(606, "TASK NO FINISH") {
	},
	HAD_ACCEPT(607, "HAD ACCEPT") {
	},
	TASK_DAYIY_FULL(608, "TASK DAYIY FULL") {
	},
	MAX_CHAT_LENTH(609, "MAX CHAT LENTH") {
	},
	MAX_SCIENCE_QUE(610, "MAX SCIENCE QUE") {
	},
	TARGET_NOT_ONLINE(611, "TARGET NOT ONLINE") {
	},
	NO_REPORT(612, "NO THIS REPORT") {
	},
	LIVE_NO_ENOUGH(613, "LIVE NO ENOUGH") {
	},
	NOT_SAME_PARTY(614, "NOT SAME PARTY") {
	},
	IN_WIPE(615, "IN WIPE") {
	},
	NOT_IN_WIPE(616, "NOT IN WIPE") {
	},
	LEFT_ONE_MEMBER(617, "LEFT ONE MEMBER") {
	},
	GIFT_HAD_GOT(618, "GIFT HAD GOT") {
	},
	COUNT_NOT_ENOUGH(619, "COUNT NOT ENOUGH") {
	},
	ATTACK_FREE(620, "CAN'T ATTACK OR SCOUT") {
	},
	HAD_APPLY(621, "HAD APPLY") {
	},
	PARTY_RECRUIT_CD(622, "CAN'T RECRUIT IN 30 MINUTE") {
	},
	GIFT_CODE_LENTH(623, "GIFT CODE LENTH ERROR") {
	},
	GIFT_CODE_FORMAT(624, "GIFT CODE FORMAT ERROR") {
	},
	ACTIVITY_NOT_FINISH(625, "ACTIVITY_NOT_FINISH") {
	},
	ACTIVITY_NOT_OPEN(626, "ACTIVITY_NOT_OPEN") {
	},
	GIFT_CODE_INVALID(627, "GIFT CODE INVALID") {
	},
	INVALID_POS(628, "INVALID POS") {
	},
	CHAT_CD(629, "IN CHAT CD TIME") {
	},
	PART_NOT_ENOUGH(630, "PART NOT ENOUGH") {
	},
	OL_NOT_ENOUGH(631, "ONLINE TIME NOT ENOUGH") {
	},
	ACTIVITY_GOT(632, "ACTIVITY GOT") {
	},
	CHAT_SILENCE(633, "YOU ARE SILENCE") {
	},
	NO_AUTHORITY(634, "NOT HAVE AUTHORITY") {
	},
	IN_SAME_PARTY(635, "IN SAME PARTY") {
	},
	IN_COLLECT(636, "IN COLLECT") {
	},
	TIME_NOT_ENOUGH(637, "TIME NOT ENOUGH") {
	},
	PARTY_LV_ERROR(638, "PARTY LV ERROR") {// 不能超过军团大厅等级
	},
	SCIENCE_LV_ERROR(639, "PARTY LV ERROR") {// 不能超过军团大厅等级
	},
	ALREADY_REG(640, "ALREADY REG PARTY WAR") {
	},
	OUT_REG_TIME(641, "OUT REG TIME") {
	},
	NOT_ON_RANK(642, "NOT ON RANK") {
	},
	IN_WAR(643, "IN WAR") {
	},
	IN_PARTY_TIME(644, "NEED 24 HOURS") {
	},
	MAX_BLESS_LV(645, "MAX BLESS LV") {
	},
	BOSS_STATE(646, "NOT IN BOSS STATE") {
	},
	BOSS_END(647, "BOSS END") {
	},
	BOSS_CD(648, "BOSS CD") {
	},
	BOSS_FORM(649, "NO BOSS FORM") {
	},
	WAR_PROCESS(650, "WAR IN PROCESS") {
	},
	BOSS_NOT_END(651, "BOSS NOT END") {
	},
	BUY_ONLY_ONCE(652, "BUY ONLY ONCE") {
	},
	ARENA_ERROR(653, "ARENA ERROR") {
	},
	NEED_LV_15(654, "NEED_LV_15") {
	},
	STAFFING_NOT_OPEN(655, "STAFFING NOT OPEN") {
	},
	SENIOR_MINE_DAY(656, "SENIOR NOT OPEN TODAY") {
	},
	SENIOR_ATTACK_1(657, "CAN'T OCCUPA") {
	},
	SENIOR_ATTACK_2(658, "CAN'T ROB") {
	},
	NO_SENIOR_COUNT(659, "SENIOR COUNT NOT ENOUGH") {
	},
	SENIOR_MINE_NOT_END(660, "SENIOR MINE NOT END") {
	},
	NOT_ON_SCORE_RANK(661, "NOT ON SCORE RANK") {
	},
	ALREADY_GET_AWARD(662, "ALREADY GET AWARD") {
	},
	FUNCTION_NO_OPEN(663, "FUNCTION_NO_OPEN") {
	},
	SCORE_NOT_ENOUGH(664, "SCORE_NOT_ENOUGH") {
	},
	TOPUP_NOT_ENOUGH(665, "TOPUP_NOT_ENOUGH") {
	},
	REFRESH_FAIL(666, "REFRESH_FAIL") {
	},
	PARTY_NAME_IS_EXIST(667, "PARTY_NAME_IS_EXIST") {// 军团名已存在
	},
	HERO_STAR_NOT_SAME(668, "HERO_STAR_NOT_SAME") {// 武将等级不一致
	},
	HERO_STAR_ERROR(669, "HERO_STAR_ERROR") {// 将星不可超过银
	},
	COUNT_ERROR(670, "COUNT_ERROR") {// 数量不对
	},
	PART_LOCKED(671, "PART_LOCKED") {// 配件已锁定
	},
	PRAY_EXIST(672, "PRAY_EXIST") {// 已祝福
	},
	NO_PRAY(673, "NO_PRAY") {// 未祝福
	},
	SCIENCE_FIT_SCOPE_IS_NOT_RIGHT(674,"SCIENCE_FIT_SCOPE_IS_NOT_RIGHT"){//军工科技装载范围不对
	},
	SCIENCE_FIT_POS_IS_NOT_RIGHT(675,"SCIENCE_FIT_POS_IS_NOT_RIGHT"){//装载的位置不存在
	},
	SCIENCE_POS_CAN_NOT_FIT(676,"SCIENCE_POS_CAN_NOT_FIT"){//该位置不能装载军工科技
	},
	SCIENCE_Military_NOT_ENOUGH(677,"SCIENCE_Military_NOT_ENOUGH"){// 军工材料不够
	},
	SCIENCE_RefitTank_UN_ACTIVE(678,"SCIENCE_RefitTank_UN_ACTIVE"){// 军工改造未激活
	},
	SCIENCE_RefitTank_NO_CONFIG(679,"SCIENCE_RefitTank_NO_CONFIG"){// 未配置该坦克改造信息
	},
	SCIENCE_MILITARY_NO_CONFIG(680,"SCIENCE_MILITARY_NO_CONFIG"){// 未配置该军工科技信息
	},
	SCIENCE_THE_POS_UN_LOCK_NO_CONFIG(681,"SCIENCE_THE_POS_UN_LOCK_NO_CONFIG"){// 该位置没有配置解锁信息
	},
	SCIENCE_UN_LOCK_Material_NOT_ENOUGTH(682,"SCIENCE_UN_LOCK_Material_NOT_ENOUGTH"){// 解锁军工格子材料不够	
	},
	SCIENCE_NO_GRID_NEED_UN_LOCK(683,"SCIENCE_NO_GRID_NEED_UN_LOCK"){//没有需要解锁格子
	},
	SCIENCE_UN_BEGIN_CAUSE_LEVEL(684,"SCIENCE_UN_BEGIN_CAUSE_LEVEL"){//等级未达到开启军工副本等级条件
	},
	SCIENCE_LOCKED(685,"SCIENCE_LOCKED"){// 军工科技未解锁
	},
	SCIENCE_LEVEL_MAX_LIMIT(686,"SCIENCE_LEVEL_MAX_LIMIT"){//军工科技等级上限
	},
	SCIENCE_NO_INIT(687,"SCIENCE_NO_INIT"){//军工科技未初始化
	},
	SCIENCE_LEVE_CAN_NOT_FIT(688,"SCIENCE_LEVE_CAN_NOT_FIT"){//军工科技等级为0不可装配
	},
	;
	public int getCode() {
		return code;
	}

	public void setCode(int code) {
		this.code = code;
	}

	public String getMsg() {
		return msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}

	private GameError(int code, String msg) {
		this.code = code;
		this.msg = msg;
	}

	private int code;
	private String msg;
}
